print("Mano darbas, kuri sunkiai dirbu")
print("Mano darbas, kuri sunkiai dirbu")
print("Mano darbas, kuri sunkiai dirbu")
print("Mano darbas, kuri sunkiai dirbu")
print("Mano darbas, kuri sunkiai dirbu")
print("Mano darbas, kuri sunkiai dirbu")
